#!/bin/sh
##############################################
# doScan - Scan WiFi channels
##############################################

#wifiIfName="wlp0s20u3u4"
#wifiIfName="wlp0s20u14"
#wifiIfName="wlp0s20u3u4"
#wifiIfName="wlp0s20u1"

#wifiIfName=wlan0
## wifiIfName=`iwconfig 2>&1 | grep wlan | grep "IEEE 802.11" | grep "ESSID:off.any" | head -1 | awk '{ print $1 }'`
#wifiIfName=`iwconfig 2>&1 | grep "IEEE 802.11" | grep "ESSID:off.any" | head -1 | awk '{ print $1 }'`
wifiIfName=`iwconfig 2>&1 | grep "IEEE 802.11" | grep "ESSID:off.any" | tail -1 | awk '{ print $1 }'`

if [ -n ""$wifiIfName"" ]
then
	echo
	# So far, mon0 always winds up being the interface name + "mon" tacked on the end
	mon0="${wifiIfName}mon"
	echo "Using adapters ${wifiIfName} and ${mon0}..."
else
	echo
	echo "NO suitable (and/or unassociated) WiFi adapter found."
	echo "Exiting."
	echo
	exit 2
fi




shutdown()
{
	killall rotateFreqs
	airmon-ng stop $mon0
	# NOTE: The above command terminates all processes (tcpdump, etc) using the $mon0 interface,
	#       so no need to kill them "individually" once the above command is issued.
	ifconfig $wifiIfName up
}

trap "shutdown;exit 0" 0 1 2 3 6 12 15


airmon-ng start ${wifiIfName}

ifconfig $mon0 promisc
dumpcap -I -c 4 -i $mon0
./rotateFreqs $mon0 2>/dev/null &

# NEW 2018-02-14 -
sleep 5
tcpdump -i $mon0 -w /tt/scan.$$.pcap &
sleep 5


# Probe for ANY transmitter talking to (or as) the A.P. -
#tcpdump -i $mon0 -e -s 256 type mgt subtype probe-resp or subtype probe-req | awk '{

# Beacons from A.P.s (nothing from clients) -
tcpdump -i $mon0 -e -s 256 type mgt subtype beacon | awk '{


##printf("\nDEBUG: [[%s]]\n",$0);

##if ((NF > 22) && ($17 == "Request")) {
if ((NF > 22) && ($18 == "Beacon")) {

	CH=$4" "$5
	# 2.4 GHz -
	if ($4 == "2412") CH="CH 1"
	if ($4 == "2417") CH="CH 2"
	if ($4 == "2422") CH="CH 3"
	if ($4 == "2427") CH="CH 4"
	if ($4 == "2432") CH="CH 5"
	if ($4 == "2437") CH="CH 6"
	if ($4 == "2442") CH="CH 7"
	if ($4 == "2447") CH="CH 8"
	if ($4 == "2452") CH="CH 9"
	if ($4 == "2457") CH="CH 10"
	if ($4 == "2462") CH="CH 11"
	if ($4 == "2467") CH="CH 12"
	if ($4 == "2472") CH="CH 13 **"
	if ($4 == "2484") CH="CH 14 **"

	# 5 GHz -
	if ($4 == "5180") CH="CH 36"
	if ($4 == "5190") CH="CH 38"
	if ($4 == "5200") CH="CH 40"
	if ($4 == "5210") CH="CH 42"
	if ($4 == "5220") CH="CH 44"
	if ($4 == "5230") CH="CH 46"
	if ($4 == "5240") CH="CH 48"
	if ($4 == "5745") CH="CH 149"
	if ($4 == "5755") CH="CH 151"
	if ($4 == "5765") CH="CH 153"
	if ($4 == "5775") CH="CH 155"
	if ($4 == "5785") CH="CH 157"
	if ($4 == "5795") CH="CH 159"
	if ($4 == "5805") CH="CH 161"
	if ($4 == "5825") CH="CH 165"

	dbm=substr($7,1,length($7)-3)
	num++
	vals[num] = 0 + dbm
	printf("%s,%s,%s,%s,", $1,CH,dbm,$11);
	for (i=19;i <= NF;i++) {
		printf("%s",$i)
		if ($i ~/\)$/) break;
		else printf(" ")
	}
	printf("\n");
};
if ((NF > 22) && ($21 == "Response")) {
	printf("%s,%s,%s,%s,%s,",$1,CH,$7,$11,$14);
	for (i=22;i <= NF;i++) {
		printf("%s",$i)
		if ($i ~/\)$/) {
			## Walk remaining fields looking for "CH:", then print the following field and break
			#for(;i <= NF; i++) {
			#	if (($i == "CH:") && (i < NF)) printf(" %s %s",$i,$(i+1))
			#}
			break;
		}
		else printf(" ")
	}
	printf("\n");
};

}'

exit 0


   $1           $2  $3    $4  $5   $6  $7    $8      $9   $10      $11          $12         $13               
23:25:58.487281 1.0 Mb/s 2432 MHz 11b -88dB signal antenna 1 BSSID:Broadcast DA:Broadcast SA:00:1e:8f:60:58:d5
 $14   $15     $16    $17     $18
(oui Unknown) Probe Request (KPQT2) [1.0 2.0 5.5 11.0 6.0 9.0 12.0 18.0 Mbit]



   $1           $2  $3    $4  $5   $6  $7    $8      $9   $10       $11              $12   $13      $14
23:25:57.785455 6.0 Mb/s 5765 MHz 11a -84dB signal antenna 1 BSSID:b0:7f:b9:96:53:40 (oui Unknown) DA:54:60:09:98:03:62
 $15  $16        $17                $18   $19     $20    $21        $22-$(22+x)
(oui Unknown) SA:b0:7f:b9:96:53:40 (oui Unknown) Probe Response (MySpectrumWiFi42-5G) [6.0* 9.0 12.0* 18.0 24.0* 36.0 48.0 54.0 Mbit], PRIVACY[|802.11]


   $1           $2  $3    $4  $5   $6  $7    $8      $9   $10       $11              $12   $13      $14
23:26:00.172137 1.0 Mb/s 2412 MHz 11b -88dB signal antenna 1 BSSID:dc:ef:09:e3:3e:95 (oui Unknown) DA:f8:04:2e:3f:69:77
 $15  $16        $17                $18   $19     $20    $21      $22-$(22+x)
(oui Unknown) SA:dc:ef:09:e3:3e:95 (oui Unknown) Probe Response (NETGEAR44) [1.0* 2.0* 5.5* 11.0* 6.0 9.0 12.0 18.0 Mbit] CH: 1, PRIVACY[|802.11]


   $1           $2  $3    $4  $5   $6  $7    $8      $9   $10       $11              $12   $13      $14
23:26:02.858974 1.0 Mb/s 2462 MHz 11b -76dB signal antenna 1 BSSID:b0:05:94:76:0e:71 (oui Unknown) DA:f8:04:2e:de:c1:f1
 $15  $16        $17                $18   $19     $20    $21        $22-$(22+x)
(oui Unknown) SA:b0:05:94:76:0e:71 (oui Unknown) Probe Response (PS4-16B523BF60B9) [1.0* 2.0* 5.5* 11.0* 6.0 9.0 12.0 18.0 Mbit] CH: 11, PRIVACY

