#!/bin/sh
##############################################
# rotateFreqs - Manually cause a "promiscuous mode" WiFi adapter to rotate channels
##############################################

wifiIfName=$1
toldEm=0

while true  
do  
    sawError=0
    # 2.4 GHz Channel Numbers - 1 2 3 4 5 6 7 8 9 10 11 12 13
    # 5 GHz Channel Numbers (LO)  - 36 38 40 42 44 46 48
    # 5 GHz Channel Numbers (HI)  - 149 151 153 155 157 159 161
    for channel in 1 2 3 4 5 6 7 8 9 10 11 12 13 36 38 40 42 44 46 48 149 151 153 155 157 159 161
    do
        iwconfig ${wifiIfName} channel $channel
	result=$?
	#echo "DEBUG: Result: $result"
	if [ ""$result"" -ne "0" ]
	then
		sawError=1

		if [ ""$toldEm"" = "0" ]
		then
			echo "*** FAILURE moving ${wifiIfName} to channel ${channel} ***"
			if [ ""$channel"" -gt 14 ]
			then
				echo "                (Is ${wifiIfName} even capable of moving to 5GHz channel ${channel}?)"
			fi
		fi
	else
		# Only sleep on the channel if we successfully moved over to it
        	sleep 0.05s
	fi
    done
    if [ ""$sawError"" = "1" ]
    then
	toldEm=1
    fi
done 

exit 0
